package parkingmanagerservice;

public enum StateMachine {
    INIT,
    GENERAL_CONFIGURATION,
    WAIT_FOR_GENERAL_CONFIGURATION_FINISH,
    GROUP_AND_DISPLAYS_CONFIGURATION,
    WAIT_FOR_GROUP_AND_DISPLAYS_CONFIGURATION,
    OPERATION_MODE_CONFIGURATION,
    WAIT_FOR_OPERATION_MODE_CONFIGURATION,
    STANDBY;

}
