package parkingmanagerservice;

public enum StateMachine {
    INIT,
    WAIT_FOR_INITIAL_CONNECTION,
    GENERAL_CONFIGURATION,
    WAIT_FOR_GENERAL_CONFIGURATION_FINISH,
    SENSORS_CONFIGURATION,
    WAIT_FOR_AUTO_SENSOR_RESPONSE,
    GET_SENSORS_DATA_FOR_AUTO_BUILD,
    WAIT_FOR_SENSORS_DATA_RESPONSE,
    BUILD_DATA_TREE_FROM_AUTO_CONFIGURATION,
    WAIT_FOR_SENSORS_CONFIGURATION,
    GROUP_AND_DISPLAYS_CONFIGURATION,
    WAIT_FOR_GROUP_AND_DISPLAYS_CONFIGURATION,
    OPERATION_MODE_CONFIGURATION,
    WAIT_FOR_OPERATION_MODE_CONFIGURATION,
    STANDBY,
    REQ_MODE_WAIT_FOR_TIMER,
    REQ_MODE_REQUEST_STATUS,
    REQ_MODE_WAIT_FOR_STATUS,
    ON_EVENT_MODE_REQUEST_STATUS,
    ON_EVENT_MODE_WAIT_FOR_STATUS,
    ON_EVENT_MODE_STANDBY,
    T_TIME_MODE_STANDBY


}
